# Generated by Django 2.2.4 on 2019-09-04 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_short_name', models.CharField(max_length=10)),
                ('legacy_id', models.CharField(blank=True, max_length=15)),
                ('active', models.BooleanField()),
            ],
            options={
                'ordering': ('active', 'legacy_id'),
            },
        ),
        migrations.CreateModel(
            name='CourseHoleDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole_num', models.PositiveSmallIntegerField()),
                ('men_par', models.PositiveSmallIntegerField()),
                ('men_hcp', models.PositiveSmallIntegerField()),
                ('ladies_par', models.PositiveSmallIntegerField()),
                ('ladies_hcp', models.PositiveSmallIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
            options={
                'ordering': ('course', 'hole_num'),
            },
        ),
    ]
