# Generated by Django 2.2.4 on 2019-09-04 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseHoleDetails',
            new_name='CourseHoleDetail',
        ),
    ]
