# Generated by Django 2.2.4 on 2019-09-03 21:50

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('bye_team', models.BooleanField()),
                ('comment', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Golfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('suffix', models.CharField(max_length=6)),
                ('identifier', models.CharField(max_length=3)),
                ('tees', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Phone', max_length=31)),
                ('active', models.BooleanField()),
                ('role', models.CharField(choices=[('M', 'Team Member'), ('C', 'Team Captain'), ('S', 'Substitute')], default='M', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golfers.Team')),
            ],
            options={
                'ordering': ('lastname', 'firstname', 'identifier'),
            },
        ),
    ]
