# Generated by Django 2.2.4 on 2019-09-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfers', '0003_auto_20190903_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfer',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
