# Generated by Django 2.2.4 on 2019-09-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golfers', '0006_auto_20190903_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='legacy_id',
            field=models.SmallIntegerField(null=True),
        ),
    ]
